title: <p align="center"> Kevin Bates </p>
#description: Data Analyst Portfolio
logo: /profile.png
description:
  <p align="center">
  <a href="pdf/KevinBates_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kevinjbts/">LinkedIn</a> |
  <a href="https://github.com/kevinjbts">GitHub</a>
  </p>
  
  <p align="justify">
  8+ Years experience in Data & Strategy with a focus on Emerging Strategy & Innovation
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
baseurl: kevinjbts_portfolio
